// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/set-playground": {
    params: {};
  };
  "/launch-editor": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/video-player": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/exercises": {
    params: {};
  };
  "/login-sse": {
    params: {};
  };
  "/processes": {
    params: {};
  };
  "/progress": {
    params: {};
  };
  "/admin+": {
    params: {};
  };
  "/start": {
    params: {};
  };
  "/theme": {
    params: {};
  };
  "/apps": {
    params: {};
  };
  "/diff": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/og": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/set-playground" | "/launch-editor" | "/sitemap.xml" | "/robots.txt" | "/video-player" | "/onboarding" | "/exercises" | "/login-sse" | "/processes" | "/progress" | "/admin+" | "/start" | "/theme" | "/apps" | "/diff" | "/test" | "/og" | "/*";
  };
  "routes/set-playground.tsx": {
    id: "routes/set-playground";
    page: "/set-playground";
  };
  "routes/launch-editor.tsx": {
    id: "routes/launch-editor";
    page: "/launch-editor";
  };
  "routes/sitemap[.]xml.ts": {
    id: "routes/sitemap[.]xml";
    page: "/sitemap.xml";
  };
  "routes/robots[.]txt.ts": {
    id: "routes/robots[.]txt";
    page: "/robots.txt";
  };
  "routes/video-player/index.tsx": {
    id: "routes/video-player";
    page: "/video-player";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/exercises.tsx": {
    id: "routes/exercises";
    page: "/exercises";
  };
  "routes/login-sse.tsx": {
    id: "routes/login-sse";
    page: "/login-sse";
  };
  "routes/processes.tsx": {
    id: "routes/processes";
    page: "/processes";
  };
  "routes/progress.tsx": {
    id: "routes/progress";
    page: "/progress";
  };
  "routes/admin+/index.tsx": {
    id: "routes/admin+";
    page: "/admin+";
  };
  "routes/_app+/index.tsx": {
    id: "routes/_app+";
    page: ;
  };
  "routes/start.tsx": {
    id: "routes/start";
    page: "/start";
  };
  "routes/theme/index.tsx": {
    id: "routes/theme";
    page: "/theme";
  };
  "routes/apps.tsx": {
    id: "routes/apps";
    page: "/apps";
  };
  "routes/diff.tsx": {
    id: "routes/diff";
    page: "/diff";
  };
  "routes/test.tsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/og.tsx": {
    id: "routes/og";
    page: "/og";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};